server:
  port: 9401  #服务端口号

eureka:
  client:
    serviceUrl:
      defaultZone: ${spring.eurekaurl}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true


spring:
  profiles:
    active: dev
  application:
    name: service-sleuth #服务名称--调用的时候根据名称来调用该服务的方法
  eurekaurl: http://127.0.0.1:9101/eureka/


---
spring:
  profiles: dev
  configurl: https://github.com/huangdingke/msc-config-client.git
---
spring:
  profiles: test
  configurl: https://github.com/huangdingke/msc-config-client.git
---